
#pragma once

//2016.12.27
#define DEFAULT_PANEL_WIDTH_SIZE				 174		
#define DEFAULT_PANEL_HEIGHT_SIZE				 301
#define DEFAULT_PANEL_WIDTH_LARGE_SIZE			 1219
#define DEFAULT_PANEL_HEIGHT_LARGE_SIZE			 696
#define DEFAULT_PANEL_WIDTH_MONITOR_SIZE		 308
#define DEFAULT_PANEL_HEIGHT_MONITOR_SIZE		 534

#define MAX_PANEL_DATA							  47
#define MAX_PANEL_DATA_LEN						 100

#define TIMER_UPDATE_TEMPERATURE				9000
#define TIMER_TEMPERATURE_LOG					8000
#define TIMER_TEMPERATURE_CHECK_WARRNING_OFF		1000
#define TIMER_UPDATE_TEMPERATURE_INTERVAL		3000

//2015.11.05
#define RECIPE_INFO						_T("RECIPE_INFO")
#define RECIPE_LIST_PC_					_T("RECIPE_LIST_PC_")
#define RECIPE_COUNT					_T("RECIPE_COUNT")
#define RECIPE_							_T("RECIPE_")
#define RECIPE_COMMENT					_T("RECIPE_COMMENT")
#define PLC_MODEL						_T("PLC_MODEL")
#define RECIPE_PC_						_T("RECIPE_PC_")
#define RECIPE_NO						_T("RECIPE_NO")
#define RECIPE_DEF_MAP_TYPE				_T("DEFECT_MAP_TYPE")
#define RECIPE_DEF_MAP_SIZE				_T("DEFECT_MAP_SIZE")
#define RECIPE_DEF_MAP_MAJOR_AXIS		_T("DEFECT_MAP_AXIS")
#define RECIPE_DEF_MAP_COORD_QMS		_T("DEFECT_MAP_COORD_QMS")
#define RECIPE_ALIGNPC_NO				_T("RECIPE_ALIGNPC_NO")		//2021.07.07 add by mby
enum
{
	RECIPE_DEF_MAP_ORIGIN_LT					= 1228,
	RECIPE_DEF_MAP_ORIGIN_LB						  ,
	RECIPE_DEF_MAP_ORIGIN_RT						  ,
	RECIPE_DEF_MAP_ORIGIN_RB							
};
enum
{
	RECIPE_DEF_MAP_X_Y_REVERSAL_OFF				= 1270,				
	RECIPE_DEF_MAP_X_Y_REVERSAL_ON					  ,
};
enum	//2016.12.30
{
	RECIPE_DEF_MAP_COORD_QMS_OFF				= 1272,				
	RECIPE_DEF_MAP_COORD_QMS_ON					  ,
};
#define RECIPE_CURRENT					_T("RECIPE_CURRENT")
#define RECIPE_CURRENT_NO				_T("RECIPE_CURRENT_NO")	//2018.03.09
#define KEY_LUMINANCE_RANGE				_T("Range")
#define KEY_LUMINANCE_USE_TDI_MIN		_T("UseTdiMin")
//2015.11.05

//2016.05.11 Mr.Chu						//QMS Data Making Align Fail 식별
#define ALIGN_FAIL									_T("1")
#define ADDR_NG_FLAG_LOWER_BYPASS					_T("D3654")		//Align Fail 혹은 Overlap Defect 발생 시 Bit On


//#define	ADDR_TEMPERATURE_WARNNING					_T("L425")	//2018.01.20 Comment
#define ADDR_PROC_DATA_EQ_ABI_CHKLIST1				_T("W1989")		// ￠￥eCu Check List	//W699 -> W1989 Cheng Du	
#define ADDR_PROC_DATA_EQ_AVL_CHKLIST1				_T("W1989")		// ￠￥eCu Check List	//W9C8 -> W1989 Cheng Du
#define ADDR_PROC_DATA_MONITOR_EQ_AVL_CHKLIST1		_T("W599")		// ￠￥eCu Check List

#define ADDR_VISION_CLIENT_FOLDER_ALARM				_T("L436")

enum		//TabControl Page
{
	TAPCTRL_PAGE1 = 0,
	TAPCTRL_PAGE2	,
	TAPCTRL_PAGE3	,
	TAPCTRL_PAGE4	,
	TAPCTRL_PAGE_Max
};

enum{
	LUMINANCE_TYPE_CFCLUMINANCE		=0	,
	LUMINANCE_TYPE_CBCLUMINANCE			,
	LUMINANCE_TYPE_CFSLUMINANCE			,
	LUMINANCE_TYPE_CBSLUMINANCE			,
	LUMINANCE_TYPE_TFCLUMINANCE			,
	LUMINANCE_TYPE_TBCLUMINANCE			,
	LUMINANCE_TYPE_TFSLUMINANCE			,
	LUMINANCE_TYPE_TBSLUMINANCE			,
	LUMINANCE_TYPE_TDILUMINANCE			,
	LUMINANCE_TYPE_MAX
};
enum{
	BGRADECHECK_		=0	,
	CGRADECHECK_			,
	GRADECHECK_MAX
};
//2020.02.28 add by mby
enum{
	BUBBLESTATION_1		=0	,
	BUBBLESTATION_2			,
	BUBBLESTATION_3			,
	BUBBLESTATION_4			,
	BUBBLESTATION_5			,
	BUBBLESTATION_6			,
	BUBBLESTATION_7			,
	BUBBLESTATION_8			,
	BUBBLESTATION_9			,
	BUBBLESTATION_10		,
	BUBBLESTATION_11		,
	BUBBLESTATION_12		,
	BUBBLESTATION_MAX
};