////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Declare Algorithm DLL Interface Function
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef DEFINE_INTERFACE_BOE7_H
#define DEFINE_INTERFACE_BOE7_H

/***************************************************************************************************
 Algorithm DLL 과 Algorithm Task 간 공유가 필요한 ENUM, 구조체 등은 여기에 정의 - AVI / SVI / APP 공통 사항
***************************************************************************************************/

#pragma once

#include "Define.h"


// KSW 17.09.07 - Image 8bit 사용
#define IMAGE_MAX_GV		256

// KSW 17.09.07 - Image 12bit 사용 ( 8bit에서도 사용 가능 ... 메모리 낭비 )
//#define IMAGE_MAX_GV		4096

// KSW 17.09.07 - Hist --> UI 안넘겨줌 ( 결과 엑셀 표시 안됨 )
// 12bit 사용 시... 시간 오래 걸림...
#define USE_ALG_HIST		FALSE

// KSW 17.11.29 - 외곽 정보 ( AVI & SVI 머지 툴 )
#define USE_ALG_CONTOURS	TRUE

// KSW 17.11.29 - 외곽 정보 최대 개수
// KSW 18.02.05 - SVI 불량 크기가 큼 / 외곽 개수 늘리기 100 -> 500
#define MAX_CONTOURS		500

#define  AREA_CAM_IMG_CLASSIFY_NUM 20
//////////////////////////////////////////////////////////////////////////
// ENUM
//////////////////////////////////////////////////////////////////////////

#define WARPING_TARGET_WIDTH 912 // SVI warping size
#define WARPING_TARGET_HEIGHT 513
// [공통] 영상 ID
// 2017.06.07 NDH : APP 조명 번호 추가
enum ENUM_IMAGE_CLASSIFY
{
	// AVI
	E_IMAGE_CLASSIFY_AVI_R = 0		,	// 00 R		
	E_IMAGE_CLASSIFY_AVI_G			,	// 01 G		
	E_IMAGE_CLASSIFY_AVI_B			,	// 02 B		
	E_IMAGE_CLASSIFY_AVI_BLACK		,	// 03 BLACK	
	E_IMAGE_CLASSIFY_AVI_WHITE		,	// 04 WHITE	
	E_IMAGE_CLASSIFY_AVI_GRAY_32	,	// 05 GRAY_32	
	E_IMAGE_CLASSIFY_AVI_GRAY_64	,	// 06 GRAY_64	
	E_IMAGE_CLASSIFY_AVI_GRAY_87	,	// 07 GRAY_87
	E_IMAGE_CLASSIFY_AVI_GRAY_128	,	// 08 GRAY_128	
	E_IMAGE_CLASSIFY_AVI_DUST		,	// 09 DUST
	E_IMAGE_CLASSIFY_AVI_VTH		,	// 10 VTH
	E_IMAGE_CLASSIFY_AVI_PCD		,	// 11 PCD
	E_IMAGE_CLASSIFY_AVI_COAXIAL	,	// 12 COAXIAL
	E_IMAGE_CLASSIFY_AVI_SIDE		,	// 13 SIDE
	E_IMAGE_CLASSIFY_AVI_BACK		,	// 14 BACK

	E_IMAGE_CLASSIFY_AVI_COUNT		,	// 10 AVI Total

	//////////////////////////////////////////////////////////////////////////

	// KSW 18.02.07 - AVI Dust만 맨 끝에 있다면 동일하게 사용할 예정
	// SVI
	E_IMAGE_CLASSIFY_SVI_R = 0		,	// 00 R
	E_IMAGE_CLASSIFY_SVI_G			,	// 01 G
	E_IMAGE_CLASSIFY_SVI_B			,	// 02 B
	E_IMAGE_CLASSIFY_SVI_BLACK		,	// 03 BLACK
	E_IMAGE_CLASSIFY_SVI_WHITE		,	// 04 WHITE	
	E_IMAGE_CLASSIFY_SVI_GRAY_32	,	// 06 GRAY_32
	E_IMAGE_CLASSIFY_SVI_GRAY_64	,	// 07 GRAY_64
	E_IMAGE_CLASSIFY_SVI_GRAY_87	,	// 08 GRAY_87
	E_IMAGE_CLASSIFY_SVI_GRAY_128	,	// 09 GRAY_128

	E_IMAGE_CLASSIFY_SVI_COUNT		,	// 09 SVI Total

	//////////////////////////////////////////////////////////////////////////

	// APP
	E_IMAGE_CLASSIFY_APP_ALL = 0		,	// 00 APP All Illum			전체 조명 값 20		
	E_IMAGE_CLASSIFY_APP_RIGHT		,	// 01 APP Right Illum 2
	E_IMAGE_CLASSIFY_APP_LEFT		,	// 02 APP Left Illum 
	E_IMAGE_CLASSIFY_APP_BOTTOM		,	// 03 APP Bottom Illum 
	E_IMAGE_CLASSIFY_APP_TOP		,	// 04 APP Top Illum 
	E_IMAGE_CLASSIFY_APP_ALL2,	// 05 APP All  Illum		전체 조명 값 70 
	E_IMAGE_CLASSIFY_APP_DUST			,	// 06 APP dust Illum

	E_IMAGE_CLASSIFY_APP_COUNT		// 07 Total
};

// 2017.06.08 Align 방향 AVI/SVI/APP 공용으로 변경
// [CInspectAlign] Align 방향
enum ENUM_ALIGN_TYPE
{
	E_ALIGN_TYPE_LEFT = 0	,
	E_ALIGN_TYPE_TOP		,
	E_ALIGN_TYPE_RIGHT		,
	E_ALIGN_TYPE_BOTTOM		,
	E_ALIGN_TYPE_END
};

// 2017.06.07 NDH : GUI 쪽에서 XML 파일 하나에 AVL, ABI 통합 사용하여 Algorithm쪽도 통합 사용
// [AVI 공통] 불량 판정 결과
// 17.03.09 신규 불량 항목 추가
enum ENUM_DEFECT_JUDGEMENT
{
	//////////////////////////////////////////////////////////////////////////
	// AVI 불량 - 디스플레이 이상
	//////////////////////////////////////////////////////////////////////////

	// 디스플레이 이상 시작
	E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL_START = 0,

	E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL = E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL_START		,	// 점등 이상
	E_DEFECT_JUDGEMENT_DISPLAY_OFF						,	// 점등 아예 안된 경우 ( 컨텍불량 & Cell 이상 )
	E_DEFECT_JUDGEMENT_DISPLAY_DARK						,	// 점등 밝기 어두움
	E_DEFECT_JUDGEMENT_DISPLAY_BRIGHT					,	// 점등 밝기 밝음	
	E_DEFECT_JUDGEMENT_DISPLAY_CHOLE_ABNORMAL			,	// CHole 주변 밝기 이상
	E_DEFECT_JUDGEMENT_DUST_GROUP						,	// Group성 부유성 이물인 경우

	// 디스플레이 이상 끝
	E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL_END	= E_DEFECT_JUDGEMENT_DUST_GROUP,

	//////////////////////////////////////////////////////////////////////////
	// AVI 불량 - Point 불량
	//////////////////////////////////////////////////////////////////////////

	// Point 불량 시작
	E_DEFECT_JUDGEMENT_POINT_START,

	E_DEFECT_JUDGEMENT_POINT_DARK = E_DEFECT_JUDGEMENT_POINT_START		,	// 암점
	E_DEFECT_JUDGEMENT_POINT_BRIGHT										,	// 명점
	E_DEFECT_JUDGEMENT_POINT_WEAK_BRIGHT								,	// 약명점
	E_DEFECT_JUDGEMENT_POINT_BRIGHT_DARK								,	// 명/암점
	E_DEFECT_JUDGEMENT_POINT_DARK_SP_1									,	// Red Pattern 암점
	E_DEFECT_JUDGEMENT_POINT_DARK_SP_2									,	// Green Pattern 암점
	E_DEFECT_JUDGEMENT_POINT_DARK_SP_3									,	// Blue Pattern 암점
	E_DEFECT_JUDGEMENT_POINT_GROUP_DARK									,	// 군짐 암점
	E_DEFECT_JUDGEMENT_POINT_GROUP_BRIGHT								,	// 군집 명점
	E_DEFECT_JUDGEMENT_POINT_DIMPLE										,   // DIMPLE

	// Point 불량 끝
	E_DEFECT_JUDGEMENT_POINT_END = E_DEFECT_JUDGEMENT_POINT_DIMPLE,

	//////////////////////////////////////////////////////////////////////////
	// AVI 불량 - Line 불량
	//////////////////////////////////////////////////////////////////////////

	// Line 불량 시작
	E_DEFECT_JUDGEMENT_LINE_START,

	E_DEFECT_JUDGEMENT_LINE_X_BRIGHT = E_DEFECT_JUDGEMENT_LINE_START,	// 밝은 X라인
	E_DEFECT_JUDGEMENT_LINE_X_BRIGHT_MULT		,   // 밝은 X란인 다발
	E_DEFECT_JUDGEMENT_LINE_Y_BRIGHT			,	// 밝은 Y라인
	E_DEFECT_JUDGEMENT_LINE_Y_BRIGHT_MULT		,   // 밝은 Y라인 다발
	E_DEFECT_JUDGEMENT_LINE_X_DARK				,	// 어두운 X라인
	E_DEFECT_JUDGEMENT_LINE_X_DARK_MULT			,	// 어두운 X라인 다발
	E_DEFECT_JUDGEMENT_LINE_Y_DARK				,	// 어두운 Y라인
	E_DEFECT_JUDGEMENT_LINE_Y_DARK_MULT			,	// 어두운 Y라인 다발
	E_DEFECT_JUDGEMENT_LINE_X_OPEN				,	// 길이가 짧은 X라인
	E_DEFECT_JUDGEMENT_LINE_Y_OPEN_RIGHT		,	// 오른 쪽 길이가 짧은 Y라인	
	E_DEFECT_JUDGEMENT_LINE_Y_OPEN_LEFT			,	// 왼 쪽 길이가 짧은 Y라인	
	E_DEFECT_JUDGEMENT_LINE_DGS					,	// X, Y 동시에 존재
	E_DEFECT_JUDGEMENT_LINE_DGS_X				,	// X, Y 동시에 존재
	E_DEFECT_JUDGEMENT_LINE_DGS_Y				,	// X, Y 동시에 존재
	E_DEFECT_JUDGEMENT_XLINE_SPOT				,	// X Line 위에 Point
	E_DEFECT_JUDGEMENT_YLINE_SPOT				,	// Y Line 위에 Point
	E_DEFECT_JUDGEMENT_LINE_X_EDGE_BRIGHT		,	// EDGE에 있는 밝은 X LINE
	E_DEFECT_JUDGEMENT_LINE_Y_EDGE_BRIGHT		,	// EDGE에 있는 밝은 Y LINE
	E_DEFECT_JUDGEMENT_LINE_CRACK_RIGHT			,	// Crack Pattern에서 오른쪽 Crack Line
	E_DEFECT_JUDGEMENT_LINE_CRACK_LEFT			,	// Crack Pattern에서 왼쪽 Crack Line
	E_DEFECT_JUDGEMENT_LINE_CRACK_BOTH			,	// Crack Pattern에서 양쪽 Crack Line
	E_DEFECT_JUDGEMENT_LINE_X_DEFECT_BRIGHT		,	// 밝은 MURA성 X LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_Y_DEFECT_BRIGHT		,	// 밝은 MURA성 Y LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_X_DEFECT_DARK		,	// 어두운 MURA성 LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_Y_DEFECT_DARK		,	// 어두운 MURA성 LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_PCD_CRACK			,	// 5.99 고정 위치 BLACK, RED, BLUE PATTERN에서 생기는 불량
	E_DEFECT_JUDGEMENT_LINE_X_VTH_BRIGHT		,	// Special PATTERN 밝은 X Line 불량
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_BRIGHT		,	// Special PATTERN 밝은 Y Line 불량
	E_DEFECT_JUDGEMENT_LINE_X_VTH_DARK			,	// Special PATTERN 어두운 X Line 불량
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_DARK			,	// Special PATTERN 어두운 Y Line 불량
	E_DEFECT_JUDGEMENT_LINE_X_VTH_DEFECT_BRIGHT	,	// Special PATTERN 밝은 X Line 불량
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_DEFECT_BRIGHT	,	// Special PATTERN 밝은 Y Line 불량
	E_DEFECT_JUDGEMENT_LINE_X_VTH_DEFECT_DARK	,	// Special PATTERN 어두운 X Line 불량
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_DEFECT_DARK	,	// Special PATTERN 어두운 Y Line 불량
	E_DEFECT_JUDGEMENT_LINE_VTH_DGS				,	// Special PATTERN DGS 불량
	E_DEFECT_JUDGEMENT_LINE_VTH_DGS_X			,	// Special PATTERN DGS X Line 불량
	E_DEFECT_JUDGEMENT_LINE_VTH_DGS_Y			,	// Special PATTERN DGS Y Line 불량
	E_DEFECT_JUDGEMENT_LINE_ETC_4				,	// LINE DEFECT BUFFER4
	E_DEFECT_JUDGEMENT_MURANORMAL_TYPE2_F_GRADE	,	// LINE DEFECT BUFFER5
	E_DEFECT_JUDGEMENT_MURANORMAL_TYPE3_F_GRADE	,	// LINE DEFECT BUFFER6

	// Line 불량 끝
	E_DEFECT_JUDGEMENT_LINE_END = E_DEFECT_JUDGEMENT_MURANORMAL_TYPE3_F_GRADE,

	//////////////////////////////////////////////////////////////////////////
	// AVI & SVI 불량 - Mura 불량
	//////////////////////////////////////////////////////////////////////////

	// Mura 불량 시작
	E_DEFECT_JUDGEMENT_MURA_START,

	E_DEFECT_JUDGEMENT_MURA_MULT_BP = E_DEFECT_JUDGEMENT_MURA_START,	// Point 불량 Gray 패턴 근접인경우 ( 백점 비슷 )
	E_DEFECT_JUDGEMENT_MURA_BLACK_SPOT			,	// 스팟 암점
	E_DEFECT_JUDGEMENT_MURA_WHITE_SPOT			,	// 스팟 명점	
	E_DEFECT_JUDGEMENT_MURA_CORNER_CM			,	// 코너 혼색
	E_DEFECT_JUDGEMENT_MURA_UP_CM				,	// 상하 혼색
	E_DEFECT_JUDGEMENT_MURA_FINGER_CM			,	// 손가락 혼색
	E_DEFECT_JUDGEMENT_MURA_LINE_X				,	// 줄무라
	E_DEFECT_JUDGEMENT_MURA_LINE_Y				,	// 줄무라
	E_DEFECT_JUDGEMENT_MURA_WHITE				,	// 백무라
	E_DEFECT_JUDGEMENT_MURA_CLOUD				,	// 
	E_DEFECT_JUDGEMENT_MURA_E_WHITE_SPOT		,	// 하부찍힘	 
	E_DEFECT_JUDGEMENT_MURA_TYPE4				,	// Tpye4 Mura Test
	E_DEFECT_JUDGEMENT_MURA_TYPE3_SMALL			,	// Type3 작은 오염물
	E_DEFECT_JUDGEMENT_MURA_TYPE3_BIG			,	// Type3 큰 오염물
	E_DEFECT_JUDGEMENT_MURA_TYPE3_RING			,	// Type3 Ring Mura
	E_DEFECT_JUDGEMENT_MURA_TEMP7				,	
	E_DEFECT_JUDGEMENT_MURA_TEMP8				,	
	E_DEFECT_JUDGEMENT_MURA_EMP					,	// EMP
	E_DEFECT_JUDGEMENT_MURA_EMD_BRIGHT			,	// EMD
	E_DEFECT_JUDGEMENT_MURA_EMD_DARK			,	// EMD
	E_DEFECT_JUDGEMENT_MURA_BN_CORNER			,	// 코너 번트
	E_DEFECT_JUDGEMENT_MURA_STAMPED				,	// 하부 찍힘
	E_DEFECT_JUDGEMENT_MURA_NUGI				,	// 누기
	E_DEFECT_JUDGEMENT_MURA_EDGE_NUGI			,	// 엣지 누기
	E_DEFECT_JUDGEMENT_MURA_EDGE_NUGI_			,	// 엣지 누기
	E_DEFECT_JUDGEMENT_MURA_AMORPH_BRIGHT		,	// 밝은 무정형
	E_DEFECT_JUDGEMENT_MURA_AMORPH_DARK			,	// 어두운 무정형
	E_DEFECT_JUDGEMENT_MURA_AMORPH_SMALL_DARK	,	// 
	E_DEFECT_JUDGEMENT_MURA_BOX_SCRATCH			,	//
	E_DEFECT_JUDGEMENT_MURA_CM					,	// 혼색 ( SVI 사용 )
	E_DEFECT_JUDGEMENT_MURA_LINEMURA_X			,	// G64 TYPE2 XLINE
	E_DEFECT_JUDGEMENT_MURA_LINEMURA_Y			,	// G64 TYPE2 YLINE
	E_DEFECT_JUDGEMENT_MURA_TYPE1MURA_X			,	// G64 TYPE1 XLINE
	E_DEFECT_JUDGEMENT_MURA_TYPE1MURA_Y			,	// G64 TYPE1 YLINE
	E_DEFECT_JUDGEMENT_MURANORMAL_NOTCH_DEFECT	,

	// Mura 불량 끝
	E_DEFECT_JUDGEMENT_MURA_END = E_DEFECT_JUDGEMENT_MURANORMAL_NOTCH_DEFECT,

	//////////////////////////////////////////////////////////////////////////
	// AVI 불량 - Bin2 용어 사용하지 말것 -> ReTest 수정
	//////////////////////////////////////////////////////////////////////////

	// ReTest 불량 시작
	E_DEFECT_JUDGEMENT_RETEST_START,

	E_DEFECT_JUDGEMENT_RETEST_POINT_DARK = E_DEFECT_JUDGEMENT_RETEST_START,	// ReTest 명점
	E_DEFECT_JUDGEMENT_RETEST_POINT_BRIGHT		,	// ReTest 암점Point
	E_DEFECT_JUDGEMENT_RETEST_LINE_BRIGHT		,	// ReTest 밝은 라인
	E_DEFECT_JUDGEMENT_RETEST_LINE_DARK			,	// ReTest 어두운 라인
	E_DEFECT_JUDGEMENT_RETEST_MURA				,	// ReTest 무라
	E_DEFECT_JUDGEMENT_RETEST_MURA_BRIGHT		,	// ReTest 밝은 무라

	// ReTest 불량 끝
	E_DEFECT_JUDGEMENT_RETEST_END = E_DEFECT_JUDGEMENT_RETEST_MURA_BRIGHT,

	//////////////////////////////////////////////////////////////////////////
	// APP 관련 불량
	//////////////////////////////////////////////////////////////////////////

	// APP 불량 시작
	E_DEFECT_JUDGEMENT_APP_START,
	
	E_DEFECT_JUDGEMENT_APP_CUTTING	 = E_DEFECT_JUDGEMENT_APP_START	,	// Cutting  
	E_DEFECT_JUDGEMENT_APP_CUT_C_COME_OUT			,	// C-Cut 돌출
	E_DEFECT_JUDGEMENT_APP_CUT_C_COME_IN			,	//		 패임
	E_DEFECT_JUDGEMENT_APP_MEASURE					,
	E_DEFECT_JUDGEMENT_APP_PAD_BURNT				,
	E_DEFECT_JUDGEMENT_APP_PAD_SCRATCH				,
	E_DEFECT_JUDGEMENT_APP_PAD_DUST					,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_BUBBLE			,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_SUBSTANCE			,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_BUBBLESUBSTANCE	,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_SCRATCH			,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_MURA				,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_HILL				,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_FILM_PEELING		,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_DUST				,
	E_DEFECT_JUDGEMENT_APP_CURL                     ,
	

// APP 불량 끝
	E_DEFECT_JUDGEMENT_APP_END = E_DEFECT_JUDGEMENT_APP_CURL,

	//////////////////////////////////////////////////////////////////////////

	E_DEFECT_JUDGEMENT_COUNT						// 총 갯수
};

enum ENUM_PANEL_DEFECT_TREND
{
	E_DEFECT_BP_PLUS_DP					= E_DEFECT_JUDGEMENT_COUNT,
	E_DEFECT_BP_DP_WB_BD_GD_GB_PLUS		,
	E_DEFECT_RETEST						,
	E_DEFECT_BP_WB_GB					,

	E_PANEL_DEFECT_TREND_COUNT					// 총 개수
};

enum ENUM_ALGORITHM_NUM
{
	E_ALGORITHM_POINT		= 0	,	// 00 POINT	
	E_ALGORITHM_LINE			,	// 01 LINE	
	E_ALGORITHM_MURA			,	// 02 MURA
	E_ALGORITHM_MURA2			,	// 03 RESERVE00
	E_ALGORITHM_MURA3			,
	E_ALGORITHM_MURA4			,
	E_ALGORITHM_MURA_CHOLE		,	// 2021.01.06 HGM
	E_ALGORITHM_MURA_SCRATCH	,	// 2021.01.06 HGM
	E_ALGORITHM_SVI				,	// 04 RESERVE01
	E_ALGORITHM_MURA_NORMAL		,	// 05 RESERVE00
	E_ALGORITHM_LCP_SUBSTANCE	,	// 06 RESERVE01
	E_ALGORITHM_LCP_SCRATCH		,	// 07 RESERVE05
	E_ALGORITHM_LCP_MOISTURE	,	// 08 RESERVE06
	E_ALGORITHM_LCP_VARIANCE	,	// 08 RESERVE06
	E_ALGORITHM_LCP_CONCEALMENT ,
	E_ALGORITHM_RESERVE07		,	// 09 RESERVE07
	E_ALGORITHM_RESERVE08		,	// 10 RESERVE08
	E_ALGORITHM_RESERVE09		,	// 11 RESERVE09
	E_ALGORITHM_RESERVE10		,	// 12 RESERVE10
	E_ALGORITHM_RESERVE11		,	// 13 RESERVE11
	E_ALGORITHM_RESERVE12		,	// 14 RESERVE12
	E_ALGORITHM_NUMBER				// 15 Total
};

// KSW 17.09.26 - 파라미터 정리
enum ENUM_PARA_COMMON
{
	E_PARA_COMMON_MAX_DEFECT_COUNT		,	// 00 : 불량 최대 갯수 ( MAX_DEFECT_COUNT 보다 작게 )
	E_PARA_COMMON_IMAGE_SAVE_FLAG		,	// 01 : 알고리즘 중간결과 Image Save flag
	E_PARA_COMMON_IMAGE_SAVE_COUNT		,	// 02 : 영상 저장 순서 카운트 ( Point의 경우 함수가 두개로 나눠 짐 )
	E_PARA_COMMON_ALG_IMAGE_NUMBER		,	// 03 : 현재 Alg 영상 번호
	E_PARA_COMMON_CAMERA_NUMBER			,	// 04 : Cam Number ( 카메라 번호 / SVI )
	E_PARA_COMMON_ROI_NUMBER			,	// 05 : ROI Number ( ROI 번호 )
	E_PARA_COMMON_ALG_NUMBER			,	// 06 : 알고리즘 번호 ( nAlgorithmNumber_ )
	E_PARA_COMMON_THREAD_ID				,	// 07 : Thread ID
	E_PARA_COMMON_DRAW_DEFECT_NUM_FLAG	,	// 08 : Draw Defect Num 표시
	E_PARA_COMMON_DRAW_DUST_FLAG		,	// 09 : Draw Dust 표시 ( Point 알고리즘이 돌아야 함 )
	E_PARA_COMMON_UI_IMAGE_NUMBER		,	// 10 : UI 상 패턴 순서 영상 번호
	E_PARA_COMMON_ROTATE_ANGLE			,	// 11 : Cell 회전된 각도 ( Align 계산 값, 소수점 3자리 까지만... )
	E_PARA_COMMON_ROTATE_CENTER_X		,	// 12 : Cell 회전된 중심 x좌표
	E_PARA_COMMON_ROTATE_CENTER_Y		,	// 13 : Cell 회전된 중심 y좌표
	E_PARA_COMMON_PS_MODE				,	// 14 : 이미지 비율 (Pixel Shift Mode - 1:None, 2:4-Shot, 3:9-Shot)

	E_PARA_COMMON_TOTAL_COUNT				// Total
};


// AVI & APP ALIGN 파라미터 정리
enum ENUM_PARA_ALIGN
{
	///////////////////////////// AVI

	// LCP Align Hole 관련
	E_PARA_LCP_ALIGN_TEXT = 0,
	E_PARA_LCP_ALIGN_GAUSSIAN_SIZE,
	E_PARA_LCP_ALIGN_GAUSSIAN_SIGMA,
	E_PARA_LCP_ALIGN_TH,
	E_PARA_LCP_ALIGN_ROUND_IN_SZ,
	E_PARA_LCP_ALIGN_ROUND_OUT_SZ,
	E_PARA_LCP_ALIGN_MEDIAN_BLUR,
	E_PARA_LCP_ALIGN_BIGCIRCLE_MINAREA,
	E_PARA_LCP_ALIGN_HOUGHCIRCLE_TEXT,
	E_PARA_LCP_ALIGN_HOUGH_DP,
	E_PARA_LCP_ALIGN_HOUGH_MINDIST,
	E_PARA_LCP_ALIGN_HOUGH_PARAM1,
	E_PARA_LCP_ALIGN_HOUGH_PARAM2,
	E_PARA_LCP_ALIGN_HOUGH_MINRADIUD,
	E_PARA_LCP_ALIGN_HOUGH_MAXRADIUD,
	E_PARA_LCP_ALIGN_ACTIVEMASK_IN,
	E_PARA_LCP_ALIGN_HOLEMASK_OUT,

	// LCP Align Hole 관련 (투명)
	E_PARA_LCP_ALIGN_LIMPI_TEXT = 0,
	E_PARA_LCP_ALIGN_LIMPI_EDGE_TH,
	E_PARA_LCP_ALIGN_LIMPI_MEDIAN_BLUR,
	E_PARA_LCP_ALIGN_LIMPI_BIGCIRCLE_MINAREA,
	E_PARA_LCP_ALIGN_LIMPI_HOUGHCIRCLE_TEXT,
	E_PARA_LCP_ALIGN_LIMPI_HOUGH_DP,
	E_PARA_LCP_ALIGN_LIMPI_HOUGH_MINDIST,
	E_PARA_LCP_ALIGN_LIMPI_HOUGH_PARAM1,
	E_PARA_LCP_ALIGN_LIMPI_HOUGH_PARAM2,
	E_PARA_LCP_ALIGN_LIMPI_HOUGH_MINRADIUD,
	E_PARA_LCP_ALIGN_LIMPI_HOUGH_MAXRADIUD,
	E_PARA_LCP_ALIGN_LIMPI_ACTIVEMASK_IN,
	E_PARA_LCP_ALIGN_LIMPI_HOLEMASK_OUT,

	////////////////////////////////////////////////////////////////////////// 기존 AVI용
	E_PARA_CHECK_MIN_GV = 0,	// 패턴별 평균 GV 최소 밝기
	E_PARA_CHECK_MAX_GV,	// 패턴별 평균 GV 최대 밝기
	E_PARA_CHECK_AVG_GV,	// 패턴별 맞추고자 하는 밝기
	E_PARA_CHECK_AREA_FLAG,	// 면적 확인 Flag
	E_PARA_CHECK_AREA_GV,	// 설정한 GV 이상 면적이
	E_PARA_CHECK_AREA_RATIO,	// 점등 영역 중에 설정 비율 이상이면 AD
	E_PARA_CHECK_NON_DEL_FLAG,	// 비검사 영역 삭제 후, AD 검사 ( Dust 패턴 사용 X )
	E_PARA_CHECK_NON_DEL_OFFSET,	// 비검사 영역 넒혀서 제거
	E_PARA_CHECK_PATTERN_LABEL,	// Label Check

	//////////////////////////////////////////////////////////////////////////

	//LCP Align && Mask && Insp Judge관련


	E_PARA_LCP_AD_TEXT = 0,	// 텍스트 표시
	E_PARA_LCP_AD_IMAGE_NUM,	// AD 검사할 패턴 번호 ( E_IMAGE_CLASSIFY_AVI_WHITE : 4 )

	E_PARA_LCP_COLORCODE_TEXT,	// 텍스트 표시
	E_PARA_LCP_COLORCODE_NUM,	// AD 검사할 패턴 번호 ( E_IMAGE_CLASSIFY_AVI_WHITE : 4 )

	E_PARA_LCP_BACK_TEXT,	// 텍스트 표시
	E_PARA_LCP_BACK_IMAGE_NUM,	// AD 검사할 패턴 번호 ( E_IMAGE_CLASSIFY_AVI_WHITE : 4 )
	E_PARA_LCP_BACK_THRESHOLD,
	E_PARA_LCP_BACK_BIGCIRCLE_MINAREA,
	E_PARA_LCP_BACK_ROUNDIN,

	E_PARA_LCP_MASK_LABEL_TEXT,	// 일치율 ( 사용 안하는 경우 : 0 )
	E_PARA_LCP_MASK_LABEL_IMAGE_NUM, //12.14
	E_PARA_LCP_MASK_LABEL_TH,	// 최소 평균 GV
	E_PARA_LCP_MASK_LABEL_GAU_SZ,
	E_PARA_LCP_MASK_LABEL_GAU_SIG,
	E_PARA_LCP_MASK_LABEL_MAX,
	E_PARA_LCP_MASK_LABEL_MIN,
	E_PARA_LCP_MASK_LABEL_ROUND_IN,
	E_PARA_LCP_MASK_LABEL_ROUND_OUT,

	E_PARA_LCP_MASK_VACUUM_TEXT,
	E_PARA_LCP_MASK_VACUUM_IMAGE_NUM, //12.14
	E_PARA_LCP_MASK_VACUUM_IMAGE_TRESHOLD,
	E_PARA_LCP_MASK_VACUUM_IMAGE_MIN_AREA,
	E_PARA_LCP_MASK_VACUUM_IMAGE_ROUNDOUT,

	E_PARA_LCP_INSPECT_SUBSTANCE_IMAGE_TEXT,
	E_PARA_LCP_INSPECT_SUBSTANCE_IMAGE_MAIN,
	E_PARA_LCP_INSPECT_SUBSTANCE_IMAGE_COMPARE,
	E_PARA_LCP_INSPECT_SUBSTANCE_IMAGE_DUST,

	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_TEXT,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_CROP_OFFSET,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_SEG_X,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_SEG_Y,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_DEFECT_DARK_TH_RATIO,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_BG_DARK_TH_RATIO,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_AXIS_RATIO,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_AREA_RATIO,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_BG_DEFECT_SIZE,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_BG_CENTER_DEFECT_RATIO,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_CENTER_DIFF,
	E_PARA_LCP_INSPECT_SUBSTANCE_JUDGE_CENTER_DIFF_RATIO,

	E_PARA_LCP_INSPECT_MOISTURE_JUDGE_TEXT,
	E_PARA_LCP_INSPECT_MOISTURE_JUDGE_AREA_RATIO,

	E_PARA_LCP_INSPECT_VARIANCE_JUDGE_TEXT,
	E_PARA_LCP_INSPECT_VARIANCE_JUDGE_AREA_RATIO,

	E_PARA_LCP_AREA_IMG_TRANSFORM_TEXT,
	E_PARA_LCP_AREA_IMG_TRANSFORM_ORI_WIDTH,
	E_PARA_LCP_AREA_IMG_TRANSFORM_ORI_HEIGHT,
	E_PARA_LCP_AREA_IMG_TRANSFORM_X,
	E_PARA_LCP_AREA_IMG_TRANSFORM_Y,

	E_PARA_LCP_STAGE_SUBSTANCE_TEXT,
	E_PARA_LCP_STAGE_SUBSTANCE_USE_FLAG,
	E_PARA_LCP_STAGE_SUBSTANCE_BLUR_SIZE,
	E_PARA_LCP_STAGE_SUBSTANCE_THRESHOLD,
	E_PARA_LCP_STAGE_SUBSTANCE_JUDGE_RATIO,

	E_PARA_LCP_CANDIDATE_DELETE_TEXT,
	E_PARA_LCP_CANDIDATE_DELETE_FLAG,

	E_PARA_LCP_MOISTURE_SUBSTANCE_DELETE_TEXT,
	E_PARA_LCP_MOISTURE_SUBSTANCE_DELETE_FLAG,

	E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_TEXT,


		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_FLAG,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_DEGREE_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_DEGREE_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_LENGHT_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_LENGHT_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_L_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC1_L_MAX,

		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_FLAG,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_DEGREE_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_DEGREE_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_LENGHT_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_LENGHT_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_L_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_RED_SPEC2_L_MAX,

		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_FLAG,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_DEGREE_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_DEGREE_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_LENGHT_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_LENGHT_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_L_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC1_L_MAX,


		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_FLAG,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_DEGREE_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_DEGREE_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_LENGHT_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_LENGHT_MAX,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_L_MIN,
		E_PARA_LCP_SUBSTANCE_COLOR_CLASSIFY_BLUE_SPEC2_L_MAX,


	////////////////////////////////////////////////////////////////////////// 기존 AVI
	E_PARA_AD_TEXT = 0,	// 텍스트 표시
	E_PARA_AD_IMAGE_NUM						,	// AD 검사할 패턴 번호 ( E_IMAGE_CLASSIFY_AVI_WHITE : 4 )
	E_PARA_AD_RATE							,	// 일치율 ( 사용 안하는 경우 : 0 )
	E_PARA_AD_ZOOM							,	// 영상 축소 비율
	E_PARA_AD_MIN_GV						,	// 최소 평균 GV
	E_PARA_AD_MAX_GV						,	// 최대 평균 GV
	E_PARA_AD_MAX_STD						,	// 최대 표준편차
	E_PARA_AD_Y_LINE						,	// 세로줄 라인 개수
	E_PARA_AD_BLOCK_X_GV					,	// 가로 방향 GV 차이
	E_PARA_AD_BLOCK_X_AREA					,	// 가로 방향 면적 비율
	E_PARA_AD_BLOCK_Y_GV					,	// 세로 방향 GV 차이
	E_PARA_AD_BLOCK_Y_AREA					,	// 세로 방향 면적 비율

	// Size
	E_PARA_CELL_SIZE_TEXT					,	// 텍스트 표시
	E_PARA_CELL_SIZE_X						,	// 영상상 Cell 가로 길이 ( pixel )
	E_PARA_CELL_SIZE_Y						,	// 영상상 Cell 세로 길이 ( pixel )

	// Round Cell 관련
	E_PARA_ROUND_TEXT						,	// 텍스트 표시
	E_PARA_ROUND_SETTING					,	// 셋팅 플래그
	E_PARA_ROUND_USE						,	// Round 코너부 찾는 알고리즘 사용 유/무
	E_PARA_ROUND_IN							,	// Round 코너부 안쪽으로 검사 제외 영역
	E_PARA_ROUND_FIND_OFFSET				,	// Round 영역 찾는 범위 설정 ( 상,하,좌,우 )
	E_PARA_ROUND_DUST_MIN_GV				,	// Dust패턴 - 외곽 평균 채울때, 최소 평균 GV 설정
	E_PARA_ROUND_OTHER_MIN_GV				,	// Dust 이외 패턴 - 외곽 평균 채울때, 최소 평균 GV 설정

	// Camera Hole 관련
	E_PARA_CHOLE_TEXT,	// 텍스트 표시
	E_PARA_CHOLE_SETTING,	// 셋팅 플래그
	E_PARA_CHOLE_USE,	// CHole 찾는 알고리즘 ON/OFF
	E_PARA_CHOLE_IN,	// CHole 바깥쪽으로 검사 제외 영역
	E_PARA_CHOLE_FIND_OFFSET,	// CHole 영역 찾는 범위 설정 ( 상, 하, 좌, 우)
	E_PARA_CHOLE_ROI_MIN_GV,	// 점등 패턴 - CHole ROI 최소 GV 확인
	E_PARA_CHOLE_SMALL_DEFECT_SIZE,	// 작은 불량 Judgement 불량 크기 제한
	E_PARA_CHOLE_SMALL_DEFECT_OFFSET,	// 작은 불량 judgement 제거 영역 Offset
	E_PARA_CHOLE_BIG_DEFECT_OFFSET,	// 큰 불량 judgement 제거 영역 Offset
	E_PARA_CHOLE_LINE_DELETE_FLAG,	// 약시인성 라인 Defect 제거 Flag (무라 불량이 안나오는 모델의 경우 해당 기능 OFF)

	// Shift Copy 관련
	E_PARA_SHIFT_COPY_TEXT					,	// 텍스트 표시
	E_PARA_SHIFT_COPY_R						,	// x방향 ? Pixel 이동
	E_PARA_SHIFT_COPY_G						,	// y방향 ? Pixel 이동
	E_PARA_SHIFT_COPY_B						,	// x방향 반복 횟수

	// Align 관련
	E_PARA_ALIGN_TEXT						,	// 텍스트 표시
	E_PARA_ALIGN_THRESHOLD					,	// 이진화
	E_PARA_ALIGN_MORP						,	// Cell 사이 빈공간 채우기 용도
	E_PARA_ALIGN_ANGLE_ERR					,	// 해당 범위를 벗어나면 중알람 발생
	E_PARA_ALIGN_ANGLE_WAR					,	// 해당 범위를 벗어나면 경알람 발생	

	// Align 분할 Morp 관련
	E_PARA_ALIGN_PARTIAL_USE				,	// USE OFF : 0 / ON : 1
	E_PARA_ALIGN_PARTIAL_THRESHOLD			,	// 점등영역 찾기위한 용도
	E_PARA_ALIGN_PARTIAL_OUTER				,	// ROI 영역 OFFSET
	E_PARA_ALIGN_PARTIAL_LEFT_OFFSET		,	// ROI LEFT OFFSET
	E_PARA_ALIGN_PARTIAL_RIGHT_OFFSET		,	// ROI RIGHT OFFSET
	E_PARA_ALIGN_PARTIAL_TOP_OFFSET			,	// ROI TOP OFFSET
	E_PARA_ALIGN_PARTIAL_BOTTOM_OFFSET		,	// ROI BOTTOM OFFSET

	// Group 관련
	E_PARA_GROUP_TEXT						,	// 텍스트 표시
	E_PARA_GROUP_FLAG						,	// 그룹 판정 사용 유/무
	E_PARA_GROUP1_COUNT						,	// 그룹1 판정 픽셀 개수
	E_PARA_GROUP1_DIAMETER					,	// 그룹1 판정 지름
	E_PARA_GROUP1_DELETE					,	// 그룹1 제거
	E_PARA_GROUP2_COUNT						,	// 그룹2 판정 픽셀 개수
	E_PARA_GROUP2_DIAMETER					,	// 그룹2 판정 지름
	E_PARA_GROUP2_DELETE					,	// 그룹2 제거
	E_PARA_GROUP3_COUNT						,	// 그룹3 판정 픽셀 개수
	E_PARA_GROUP3_DIAMETER					,	// 그룹3 판정 지름
	E_PARA_GROUP3_DELETE					,	// 그룹3 제거

	// Pad 부 명점 임시 관련
	E_PARA_PAD_BRIGHT_TEXT					,	// 텍스트 표시
	E_PARA_PAD_BRIGHT_FLAG					,	// Pad 부 명점 
	E_PARA_PAD_BRIGHT_X						,	// Pad 부 명점 가로
	E_PARA_PAD_BRIGHT_Y						,	// Pad 부 명점 세로

	// 혼색 많이 발생 -> 약명점과 비슷한 경향을 보임 ( 개수 많은 경우 ET 판정 )
	E_PARA_HS_JUDGMENT_TEXT					,	// 텍스트 표시
	E_PARA_HS_JUDGMENT_COUNT_BRIGHT			,	// 설정 개수
	E_PARA_HS_JUDGMENT_COUNT_DARK			,	// 설정 개수

	// 누기 같은 강시인성 불량 근처에 포인트 과검이 존재
	E_PARA_STRONG_DEFECT_NOISE_TEXT			,	// 텍스트 표시
	E_PARA_STRONG_DEFECT_NOISE_ADJUST_RANGE	,	// 지울 불량에 대한 확장 범위

	// PCD_CRACK : 비검사 영역 안에 라인 불량 존재하는 경우, 불량명 수정
	E_PARA_PCD_CRACK_TEXT					,	// 텍스트 표시
	E_PARA_PCD_CRACK_FLAG					,	// PCD CRACK 사용 유/무

	// Non Insp Area
	E_PARA_NON_INSP_AREA_TEXT				,	// 텍스트 표시
	E_PARA_NON_INSP_AREA_ONLY_LINE			,	// 라인 불량인 경우만 동작

	// Dimple 판정 Ratio
	E_PARA_DIMPLE_RATIO_TEXT				,	// 텍스트 표시
	E_PARA_DIMPLE_RATIO_GRAY_Active			,	// DIMPLE 판정 Ratio Active
	E_PARA_DIMPLE_RATIO_GRAY_Edge			,	// DIMPLE 판정 Ratio Edge
	E_PARA_DIMPLE_RATIO_RGB					,	// DIMPLE 판정 Ratio

	// 한도내 Spot 제거 Ratio
	E_PARA_SISPOT_TEXT						,	// 텍스트 표시
	E_PARA_SISPOT_RATIO_ACTIVE				,	// ACTIVE SPOT 판정 RATIO 현 1로 설정
	E_PARA_SISPOT_RATIO_EDGE				,	// EDGE SPOT 판정 RATIO 현 1로 설정
	E_PARA_SISPOT_NUMBER_GVCOUNT			,	// GV COUNT
	E_PARA_SISPOT_AREA						,	// GV COUNT

	// 한도내 강시인Spot 제거 Ratio											
	E_PARA_STRONG_SISPOT_TEXT,	// 텍스트 표시
	E_PARA_STRONG_SISPOT_RATIO_ACTIVE,	// ACTIVE SPOT 판정 RATIO 현 1로 설정
	E_PARA_STRONG_SISPOT_RATIO_EDGE,	// EDGE SPOT 판정 RATIO 현 1로 설정
	E_PARA_STRONG_SISPOT_NUMBER_GVCOUNT,	// GV COUNT
	E_PARA_STRONG_SISPOT_AREA,	// GV COUNT

	// 암점 확인 Logic
	E_PARA_DUST_DARKPOINT_TEXT				,	// 텍스트 표시
	E_PARA_DUST_DARKPOINT_ONOFF				,	// ACTIVE SPOT 판정 RATIO 현 1로 설정

	// Camera Tap Overkill Delet
	E_PARA_CAMERA_TAP_OVERKILL_TEXT			,	// 텍스트 표시
	E_PARA_CAMERA_TAP_OVERKILL_ONOFF		,	// 텍스트 표시
	E_PARA_CAMERA_TAP_OVERKILL_CAMERATYPE	,	// ㅋㅋ
	E_PARA_CAMERA_TAP_OVERKILL_OFFSET		,	// 텍스트 표시

	// Norch 부 Overkill Delet
	E_PARA_NORCH_OVERKILL_TEXT				,	// 
	E_PARA_NORCH_OVERKILL_ONOFF				,	// 
	E_PARA_NORCH_OVERKILL_UNIT_X			,	// 
	E_PARA_NORCH_OVERKILL_UNIT_Y			,	// 
	E_PARA_NORCH_OVERKILL_THGV_GREEN		,	// 
	E_PARA_NORCH_OVERKILL_THGV_RB			,	// 
	E_PARA_NORCH_OVERKILL_ABS_GREEN			,	// 
	E_PARA_NORCH_OVERKILL_ABS_RB			,	// 
	E_PARA_NORCH_OVERKILL_OFFSET			,	//

	E_PARA_LASTGROUP_JUDGE_TEXT				,
	E_PARA_LASTGROUP_JUDGE_ALL_COUNT		,
	E_PARA_LASTGROUP_JUDGE_BRIGHT_COUNT		,
	E_PARA_LASTGROUP_JUDGE_DARK_COUNT		,


	// Mura Normal Classification Parameter
	E_PARA_MURANORMAL_CLASSPARA_TEXT,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE1,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE2,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE3,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE4,	//

	// Mura Normal 2nd Judgement OverKill Reduction (T3)
	E_PARA_MURANORMAL_OR_TEXT,	//
	E_PARA_MURANORMAL_OR_TYPE3_BBS_DIFFGV,	//
	E_PARA_MURANORMAL_OR_TYPE3_SBS_DIFFGV,	//
	E_PARA_MURANORMAL_OR_TYPE3_CH_DIFFGV,	//
	E_PARA_MURANORMAL_OR_TYPE3_BUBBLEMERGE,	//

	// Point - point 중복 제거 offset
	E_PARA_Duplicate_offset,

	// 2021.01.12 HGM
	// Image 회전 관련
	E_PARA_IMAGE_ROTATE_TEXT				,	// 텍스트 표시
	E_PARA_IMAGE_ROTATE						,

	///////////////////////////////// SVI

	// AD GV 관련 ( 밝기 체크 )
	E_PARA_SVI_CHECK_MIN_GV			= 0	,	// 패턴별 평균 GV 최소 밝기
	E_PARA_SVI_CHECK_MAX_GV				,	// 패턴별 평균 GV 최대 밝기

	///////////////////////////////////////////////////////////////////////////////////////////////

	// AD 관련
	E_PARA_SVI_AD_TEXT				= 0	,	// 텍스트 표시
	E_PARA_SVI_AD_IMAGE_NUM				,	// AD 검사할 패턴 번호 ( E_IMAGE_CLASSIFY_AVI_WHITE : 4 )
	E_PARA_SVI_AD_RATE					,	// 일치율 ( 사용 안하는 경우 : 0 )
	E_PARA_SVI_AD_ZOOM					,	// 영상 축소 비율
	E_PARA_SVI_AD_MIN_GV				,	// 최소 평균 GV
	E_PARA_SVI_AD_MAX_GV				,	// 최대 평균 GV
	E_PARA_SVI_AD_MAX_STD				,	// 최대 표준편차

	// Size
	E_PARA_SVI_CELL_SIZE_TEXT			,	// 텍스트 표시
	E_PARA_SVI_CELL_COAX_SIZE_X			,	// 동축 카메라 영상상 Cell 가로 길이 ( pixel )
	E_PARA_SVI_CELL_COAX_SIZE_Y			,	// 동축 카메라 영상상 Cell 세로 길이 ( pixel )
	E_PARA_SVI_CELL_SIDE_SIZE_X			,	// 사이드 카메라 영상상 Cell 가로 길이 ( pixel )
	E_PARA_SVI_CELL_SIDE_SIZE_Y			,	// 사이드 카메라 영상상 Cell 세로 길이 ( pixel )

	// Align 관련
	E_PARA_SVI_ALIGN_TEXT				,	// 텍스트 표시
	E_PARA_SVI_ALIGN_THRESHOLD			,	// 이진화

	// Round Cell 관련
	E_PARA_SVI_ROUND_TEXT				,	// 텍스트 표시
	E_PARA_SVI_ROUND_USE				,	// Round 코너부 찾는 알고리즘 사용 유/무
	E_PARA_SVI_ROUND_IN					,	// Round 코너부 안쪽으로 검사 제외 영역
	E_PARA_SVI_ROUND_SIZE				,	// Round 영역 범위 설정
	E_PARA_SVI_ROUND_DIAGONAL			,	// Round 영역 코너 설정

	E_PARA_SVI_CROP_RATIO				,


	E_PARA_SVI_TOTAL_COUNT				,	// Total


	///////////////////////////// APP

	//Curl
	E_PARA_APP_CURL_TEXT				=0	,	// 텍스트 표시
	E_PARA_APP_CURL_USE						,	// Curl Algorithm 사용
	E_PARA_APP_CURL_RANGE_X				    ,	// Profile을 몇개 씩 평균 낼 것인지
	E_PARA_APP_CURL_RANGE_Y_TOP			    ,	// Profile을 추출할 범위 사이즈 TOP
	E_PARA_APP_CURL_RANGE_Y_BOTTOM			,   // Profile을 추출할 범위 사이즈 BOTTOM
	E_PARA_APP_CURL_IMAGE_NUM				,	// Curl Algorithm에서 사용할 Image number
	E_PARA_APP_CURL_CONDITION_COUNT         ,	// 평균 Size 보다 큰 Size가 몇개 이상일 때 Curl로 판단할 것인지
	E_PARA_APP_CURL_SEARCH_RATIO        	,	// 평균 Size의 몇 배를 Curl로 판정
	E_PARA_APP_CURL_STANDARD_GV_RATIO       ,	// Curl이 시작 되는 부분이라고 잡은 기준에서 몇 % 내려와서 측정할 것인지
	E_PARA_APP_CURL_CORNER_SEARCH_COUNT	 	,	// Corner 부분의 Curl Parameter, 평균 Size 보다 큰 Size가 몇개 이상일 때 Curl로 판단할 것인지
	E_PARA_APP_CURL_CORNER_SEARCH_RATIO	    ,	// Corner 부분의 Curl Parameter, 평균 Size의 몇 배를 Curl로 판정
	E_PARA_APP_CURL_BLUR_SIZE				,	// Blur Mask Size
	E_PARA_APP_CURL_GAUSSIGMA				,	// 영상상 Cell 세로 길이 ( pixel )
	E_PARA_APP_CURL_START_OFFSET_LEFT		,	// C-Cut 부분을 제외하기 위한 검출 시작점 Offset 
	E_PARA_APP_CURL_END_OFFSET_RIGHT		,   // C-Cut 부분을 제외하기 위한 검출 끝점 Offset
	E_PARA_APP_CURL_PROFILE_SEARCH_OFFSET	,	// Profile에서 Min 값 이후로 Offset 크기를 너비로 사용한 만큼 값을 남김
	E_PARA_APP_RESERVE2						,
	E_PARA_APP_RESERVE3						,
	E_PARA_APP_PAD_EDGE_TEXT				,
	E_PARA_APP_PAD_EDGE_THETA				,

	//AD Check
	E_PARA_APP_AD_TEXT						,	// 텍스트 표시
	E_PARA_APP_AD_IMAGE_NUM					,	// AD Check 사용할 Image
	E_PARA_APP_AD_BLUR_SIZE					,	// Blur Size
	E_PARA_APP_AD_THRESHOLD					,	// 이진화 값
	E_PARA_APP_AD_LIMIT_AREA				,	// 이진 영상에서 최소로 존재해야하는 크기 조건
	E_PARA_APP_AD_GV						,	// AD Check GV 값
	
	// Align 관련
	E_PARA_APP_ALIGN_TEXT					,	// 텍스트 표시
	E_PARA_APP_ALIGN_THRESHOLD				,	// 이진화 값
	E_PARA_APP_ALIGN_DILATE					,	// 이진화 한 후 가장 큰 Blob 남긴 것에 사용하는 팽창
	E_PARA_APP_ALIGN_PANEL_EDGE_THETA		,	// Cell 외곽 Edge Detection 기준 Theta	
	E_PARA_APP_ALIGN_ANGLE_ERR				,	// 해당 범위를 벗어나면 중알람 발생
	E_PARA_APP_ALIGN_ANGLE_WAR				,	// 해당 범위를 벗어나면 경알람 발생
	E_PARA_APP_ALIGN_AVG_OFFSET				,
	E_PARA_APP_ALIGN_USE_OVERRANGE			,	// Align 후 Pannel Size 범위 벗어남 사용 유무 처리
	E_PARA_APP_ALIGN_RANGE_OVER				,	// Align 후 Pannel Size 범위 벗어나면 AD 불량처리

	//Polygon 영역 처리 관련
	E_PARA_APP_POLYGON_TEXT					,	//텍스트 표시
	E_PARA_APP_MAKE_ACTIVE_MASK				,	//Polygon Mask 만들기 Flag
	E_PARA_APP_POLYGON_IMAGE_NUM			,	//ROUND 처리 시 사용할 이미지
	E_PARA_APP_POLYGON_RESIZE				,	//Resize하는 영상 크기
	E_PARA_APP_POLYGON_GAUS_SIZE			,	//Gaussian Blur Mask 크기
	E_PARA_APP_POLYGON_GAUS_SIGMA			,	//Gaussian Blur Sigma 크기
	E_PARA_APP_POLYGON_THRESHOLD			,	//Edge 추출 후 사용하는 이진화 값
	E_PARA_APP_POLYGON_OPEN_SIZE			,	//Open 연산 Mask 크기	
	E_PARA_APP_POLYGON_SELECT_BLOB			,	//내림차순한 Blob 중 몇 번째로 큰 것을 선택할 것인지
	E_PARA_APP_POLYGON_DILATE_SIZE			,	//Dilate 연산 Mask 크기
	E_PARA_APP_POLYGON_ERODE_SIZE			,	//Erode 연산 Mask 크기
	E_PARA_APP_POLYGON_CORNER_ROI_SIZE		,	//Corner 영역 사용할 ROI 크기
	E_PARA_APP_POLYGON_BM_THETA_LT			,	//BM Line Search용 기준 각도
	E_PARA_APP_POLYGON_BM_THETA_RB			,	
	E_PARA_APP_POLYGON_BM_IGNORE_GV			,	//BM Line Search한 기준 각도 지점의 최소 GV 값 조건
	E_PARA_APP_POLYGON_BM_PRE_THRESH_RATIO	,	//BM Line Blob 남기기 전에 다른 짜잘한 Blob을 없애기 위한 Threshold 과정에서 사용하는 평균 값중 사용할 비율
	E_PARA_APP_ADGV_TEXT					,	//ADGV TEXT
	E_PARA_APP_ADGV_MEAN_GV					,	//ADGV 기준 평균 GV
	E_PARA_APP_RESERVE27					,
	E_PARA_APP_RESERVE28					,	
	E_PARA_APP_RESERVE29					,
	E_PARA_APP_RESERVE30					,
	E_PARA_APP_RESERVE31					,
	E_PARA_APP_RESERVE32					,
	E_PARA_APP_RESERVE33					,
	E_PARA_APP_RESERVE34					,

	// Align Area
	E_PARA_ALIGN_AREA_ACTIVE_L				,	// 
	E_PARA_ALIGN_AREA_ACTIVE_R				,	// 
	E_PARA_ALIGN_AREA_ACTIVE_T				,	// 
	E_PARA_ALIGN_AREA_ACTIVE_B				,	// 
	E_PARA_ALIGN_AREA_PAD_WIDTH				,	// 
	E_PARA_ALIGN_AREA_PAD_LOCATION			,	// 

	E_PARA_TOTAL_COUNT							// Total
};

enum ENUM_COLOR_CODE
{
	E_COLOR_CODE_WHITE = 0,
	E_COLOR_CODE_BLACK ,
	E_COLOR_CODE_MP ,
	E_COLOR_CODE_TRANSPARENCY ,
	E_COLOR_CODE_GRAY
};
#endif